<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Layui</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="layui/css/layui.css"  media="all">
    <!-- 注意：如果你直接复制所有代码到本地，上述css路径需要改成你本地的 -->
</head>
<body>
<div style="background-color: #1114a5; height: 100%;">
    <div class="layui-row" style="position: absolute; top: 5px; left: 5px; bottom: 5px; width: 420px;">

            <div class="layui-card" id="" style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; border: 1px solid #ccc;">
                <div class="layui-card-header" style="border-bottom: 1px solid #ccc; font-weight: bolder;">
                    系统讯息
                </div>
                <div class="layui-card-body" style="padding: 0;">
                </div>
            </div>

    </div>
    <div class="layui-row" style="position: absolute; top: 5px; left: 425px; bottom: 5px; width: 420px;">

        <div class="layui-card" id="" style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; border: 1px solid #ccc;">
            <div class="layui-card-header" style="border-bottom: 1px solid #ccc; font-weight: bolder;">
                系统讯息
            </div>
            <div class="layui-card-body" style="padding: 0;">
            </div>
        </div>

    </div>
</div>

<script src="layui/layui.js" charset="utf-8"></script>
<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
<script>

</script>
</body>
</html>